fix: break on outer call and not on nested func
Samsung/netcoredbg pull request #127
Opened 2023-06-20 11:15 UTC by noam-sol

Fixes #124

I tried to follow @viewizard advice on https://github.com/Samsung/netcoredbg/issues/124#issuecomment-1591178401 and it works nicely for the use-case described there.

I have run the test suite and they all passed (except for `VSCodeTestEvalArraysIndexers` which seems to be flaky for me on master branch anyway).

Would love to hear your thoughts, thanks!

2023-06-20 11:53 UTC, viewizard requested changes

2023-06-20 11:53 UTC, viewizard commented on src/managed/SymbolReader.cs
> +                            else if (reqPos == Position.Last && p.EndLine > nearestSP.EndLine)
We probably don't need 2 branches for `if` statement here, just use 1 with modified condition:
```
    if ((a) ||
        (b))
         nearestSP = p;
```

2023-06-20 11:53 UTC, viewizard commented on src/managed/SymbolReader.cs
> +                            else if (reqPos == Position.Last && p.EndColumn > nearestSP.EndColumn)
Same here.

2023-06-20 11:53 UTC, viewizard commented on src/managed/SymbolReader.cs
> +                        ) {
This condition looks wrong for me
```
    if ( a1>b1 || ( a1==b1 && c1>d1 ) && a2<b2 || ( a2==b2 && c2<d2 ) )
```
probably, should be
```
    if ( ( a1>b1 || ( a1==b1 && c1>d1 ) ) && ( a2<b2 || ( a2==b2 && c2<d2 ) ) )
```
instead?

2023-06-20 13:33 UTC, viewizard reviewed
Looks good for me. Let me some time, I will put your commit into our internal dev repo for CI testing and internal reviewing.

2023-06-20 14:14 UTC, noam-sol commented
@viewizard thanks! let me know if there's anything I can help out with.

2023-07-07 12:52 UTC, gbalykov commented
Fix is part of latest release

2023-07-07 12:52 UTC, closed without merging